### ISSUE TITLE
Mysql driver not working

### ISSUE THREAD

**Issue by nguyentranchung** [weareneopix/laravel-model-translation#1]
![image](https://user-images.githubusercontent.com/9611224/71231105-c1cb9080-232f-11ea-9e87-1fa34f819cfc.png)

**Comment by nguyentranchung** [comment]
![image](https://user-images.githubusercontent.com/9611224/71231135-e6c00380-232f-11ea-87d2-2c80c5ee47d8.png)

**Comment by misa-neopix** [comment]
@nguyentranchung Hey, thanks for posting. Can you please provide me with your PHP and Laravel versions? Also, when you do the actions you showed in your screenshots, does anything get persisted into the table you provided?

**Comment by nguyentranchung** [comment]
@misa-neopix 
```
php: 7.2
laravel: 6.7
database: mariadb 10.3
```

**Comment by misa-neopix** [comment]
@nguyentranchung Thanks. The package was made when Laravel 5.7 was active and a lot has changed since then. I'll look into it by the end of the weekend and hopefully refactor it to support newer versions of Laravel too.
